MAIN-103: create api key and get list of api keys
electricaio/web pull request #16
Opened 2018-11-16 20:48 UTC by nscodelover

2018-11-16 23:43 UTC, chrismccaw requested changes
I tested this locally and a key gets created 👍 

However, I found a couple of issues.

- After creating a key nothing appears in the table. If I refresh I see it.
- The build is failing because of linting and testing failures. 
- You are feeding through the userId when it doesn't need to. 
- Don't use `any` since we want the type system to catch incorrect arguments for us

You should run `npm run precommit`. This will run formatting, tests and linting. I tend to run it periodically and before creating a PR

2018-11-16 23:43 UTC, chrismccaw commented on src/modules/api-keys/components/api-keys/api-keys.tsx
> +  handleCommit = (param: any) => {
Avoid using `any`. Sometimes it might be necessary but we have the `ApiKeyModal` type which ensures we are passing the correct object around

2018-11-16 23:43 UTC, chrismccaw commented on src/modules/api-keys/components/api-keys/api-keys.tsx
> +        <ApiKeysTable data={apiKeys} userId={userId} onRemove={this.handleRemove} />
We don't need to feed through the `userId` to the child components. The `userId` should be used only when making calls to the API. 
It looks like you are passing it down so it can then be used in `handleCommit`. However `handleCommit` already has access to `userId` thought `props`

2018-11-16 23:43 UTC, chrismccaw commented on src/redux/api-keys/types.ts
> +  GET_ACCESS_KEY_SUCCESS = '@@keys/FETCH_ACCESS_KEY_SUCCESS',
The name of the action and the value are inconsistent 

`GET_ACCESS_KEY_SUCCESS = '@@keys/FETCH_ACCESS_KEY_SUCCESS',`

I would keep it as `FETCH` since that's what the other actions use

`FETCH_ACCESS_KEY_SUCCESS = '@@keys/FETCH_ACCESS_KEY_SUCCESS',`

2018-11-16 23:43 UTC, chrismccaw commented on src/redux/api-keys/actions.ts
> +export const getKey = (accessKeyId: number) => (dispatch: Dispatch) => {
missing tests

2018-11-16 23:43 UTC, chrismccaw commented on src/modules/api-keys/components/table/table.tsx
> +    data.map(el => {
This is an immutable operation so your `data` object will not have changed. If we need to had a key property then it should be added in the reducer when it is building the state

2018-11-17 17:28 UTC, nscodelover commented on src/modules/api-keys/components/api-keys/api-keys.tsx
> +  handleCommit = (param: any) => {
fixed

2018-11-17 17:28 UTC, nscodelover commented on src/modules/api-keys/components/api-keys/api-keys.tsx
> +        <ApiKeysTable data={apiKeys} userId={userId} onRemove={this.handleRemove} />
fixed

2018-11-17 17:28 UTC, nscodelover commented on src/redux/api-keys/types.ts
> +  GET_ACCESS_KEY_SUCCESS = '@@keys/FETCH_ACCESS_KEY_SUCCESS',
fixed

2018-11-17 17:29 UTC, nscodelover commented on src/redux/api-keys/actions.ts
> +export const getKey = (accessKeyId: number) => (dispatch: Dispatch) => {
added the tests

2018-11-17 17:30 UTC, nscodelover commented on src/modules/api-keys/components/table/table.tsx
> +    data.map(el => {
fixed

2018-11-18 02:14 UTC, chrismccaw requested changes

2018-11-18 02:14 UTC, chrismccaw commented on src/modules/api-keys/components/modal-button-action/modal-button-action.tsx
> +  onCommit: (param: any) => void;
This should be kept as `ApiKeyModal `

2018-11-18 02:14 UTC, chrismccaw commented on src/redux/api-keys/actions.ts
> +export const createKey = (param: any) => (dispatch: Dispatch) => {
If you make this `any` then we don't know the types that this function should accept. This goes against the power of typescript. I think the `createKey` function should look something like this `createKey(data: ApiKeyModal, userId: number)` This way we ensure that a new ApiKeyModal is passed with the required `userId`

2018-11-18 02:14 UTC, chrismccaw commented on src/redux/api-keys/reducer.ts
> +      accessKeys.map(obj => {
again, `map` is an immutable operation , so `accessKeys` data structure won't have changed. 
You should add a test to verify this behavior `obj.key = obj.name;`
Why are you setting `key` to `name` anyway?

2018-11-18 03:11 UTC, nscodelover commented on src/modules/api-keys/components/modal-button-action/modal-button-action.tsx
> +  onCommit: (param: any) => void;
oh... sorry, I really missed fixing it.

2018-11-18 03:13 UTC, nscodelover commented on src/redux/api-keys/actions.ts
> +export const createKey = (param: any) => (dispatch: Dispatch) => {
yep, right. I really missed it.

2018-11-18 03:17 UTC, nscodelover commented on src/redux/api-keys/reducer.ts
> +      accessKeys.map(obj => {
have you checked the `accessKeys` data structure didn't change? I checked it. so `accessKeys` data structure was changed. 
and we need the unique `key` property to render in table. so I used the `name` since the name is unique.

2018-11-18 04:18 UTC, chrismccaw requested changes

2018-11-18 04:18 UTC, chrismccaw commented on src/redux/api-keys/reducer.ts
> +      accessKeys.map(obj => {
That's because you are changing the `obj` ` obj.key = obj.name;` You are mutating the `obj`. It would be the same result if you used `each`
Access Keys has an `id` Can you use that?
 
I think what you are looking for is:

```      
const accessKeys = action.payload.map(obj => ({...obj, key: obj.id}));
 return { ...state, loading: true, data: accessKeys };
```

2018-11-18 18:19 UTC, chrismccaw commented on src/modules/api-keys/components/table/table.tsx
> +    tableData.map(obj => {
don't mutate like this. Do this `const dataSource = data.map(obj => ({...obj, key: obj.id}));`
Also add unit test for this

2018-11-18 21:37 UTC, chrismccaw approved these changes
Looks good 👍

2018-11-18 21:37 UTC, merged