MAIN-105 Provide an ability to sign up a new user.
electricaio/web pull request #21
Opened 2018-11-21 03:46 UTC by renerondon

## [MAIN-105](https://electricaio.atlassian.net/browse/MAIN-105)

## Description

1.) Rename User Name to Email. Make sure that the Email field is checked for Email pattern.

2.) All fields are required on this form. Remove the Company field from the form - not required.

3.) Create user by issuing a POST to the createUser API.

4.) Assume an organization_id of '1' at all times.

5.) On Successfful signup, the user should be redirected to the Login Page.

2018-11-21 17:48 UTC, chrismccaw requested changes

2018-11-21 17:48 UTC, chrismccaw commented on src/modules/signup/index.tsx
> +// import { SignupParamsType } from '../../redux/auth/types';
Remove this line if it is commented out

2018-11-21 17:48 UTC, chrismccaw commented on src/modules/signup/index.tsx
> +    form.validateFields((err: string, values: any) => {
Instead of `any` can we use `SignupParamsType` ? We should avoid using `any` as much as possible.

2018-11-21 17:48 UTC, chrismccaw commented on src/redux/auth/__tests__/actions.test.ts
> +    const params: any = {
Can we use `SignupParamsType` here?

2018-11-21 17:48 UTC, chrismccaw commented on src/redux/auth/actions.ts
> +      localStorage.setItem(AUTH_TOKENS_STORAGE_KEY, JSON.stringify(result.data));
this isn't needed `localStorage.setItem`
We should change `AxiosResponse<AUTH_TOKEN_TYPE>` to the correct type. I think right now we don't need anything so just do `dispatch(signupUserAsyncActions.success());`

2018-11-21 17:48 UTC, chrismccaw commented on src/modules/signup/container/signup.container.tsx
> +  message.error('Your signup failed');
Can you add the error message to this as well. Just so the user understands what went wrong.

2018-11-22 08:29 UTC, renerondon commented on src/modules/signup/index.tsx
> +// import { SignupParamsType } from '../../redux/auth/types';
It is removed.

2018-11-22 08:30 UTC, renerondon commented on src/modules/signup/index.tsx
> +    form.validateFields((err: string, values: any) => {
Originally, it was object but it was not able to fetch property values.
And we need to generate new object from `values` so I just made it as `any`.

2018-11-22 08:30 UTC, renerondon commented on src/redux/auth/__tests__/actions.test.ts
> +    const params: any = {
yes, I fixed it.

2018-11-22 08:30 UTC, renerondon commented on src/redux/auth/actions.ts
> +      localStorage.setItem(AUTH_TOKENS_STORAGE_KEY, JSON.stringify(result.data));
Okay, I removed it.

2018-11-22 08:32 UTC, renerondon commented on src/modules/signup/container/signup.container.tsx
> +  message.error('Your signup failed');
To where can I add this error message?

2018-11-22 22:22 UTC, chrismccaw commented on src/modules/signup/container/signup.container.tsx
> +  message.error('Your signup failed');
something like?
```
message.error(`Your signup failed {this.props.error}`)
```
Can't remember the format of the error message

2018-11-22 22:27 UTC, chrismccaw commented on src/modules/signup/index.tsx
> +    form.validateFields((err: string, values: any) => {
`SignupParamsType` should work tho? It is very beneficial to use the same typed modal from components to api

2018-11-22 22:28 UTC, chrismccaw commented on src/modules/signup/container/signup.container.tsx
> +  message.error('Your signup failed');
This isn't blocking this PR if the error formats are not there yet

2018-11-23 18:27 UTC, renerondon commented on src/modules/signup/container/signup.container.tsx
> +  message.error('Your signup failed');
That makes sense.

2018-11-23 19:47 UTC, chrismccaw approved these changes

2018-11-23 19:47 UTC, merged