MAIN-187: Ability to show access key which can be copied on clicking the show b…
electricaio/web pull request #24
Opened 2018-11-23 15:38 UTC by nscodelover

2018-11-23 23:21 UTC, chrismccaw requested changes
Looks good but added some comments to help clean things up and keep our TS modals correct

When I try out the component I get this.

<img width="1427" alt="screen shot 2018-11-23 at 2 55 39 pm" src="https://user-images.githubusercontent.com/1656770/48962332-5c8e4b80-ef33-11e8-8ab5-ff2e9eb3312a.png">

2018-11-23 23:21 UTC, chrismccaw commented on src/redux/api-keys/types.ts
> +export type ApiHiddenKeyModal = {
We should just be using ApiKeyModal instead of creating another one

2018-11-23 23:21 UTC, chrismccaw commented on src/redux/api-keys/types.ts
>    readonly data: ApiKeyModal[];
We shouldn't need to add another piece of state `hiddenKey`. All access keys should just be added to `data` then one the component side we can `find` the correct key via the `id`

2018-11-23 23:21 UTC, chrismccaw commented on src/modules/api-keys/components/table/table.tsx
> +        {this.state.showKey && (
I don't think you need `{this.state.showKey && (` since `Modal` has `visible={this.state.showKey}`

You should move this modal and any functions related to it to its own component. Similar to `src/modules/api-keys/components/modal-button-action/modal-button-action.tsx`

Lastly, I would use redux `connect` when you move out this component. Then you have a lot of flexibility on how this component operates and the data it needs from the state tree. It also keeps it completely independent from any other component so we can move it anywhere in the app.

I think it would look better to just have the `key` row have a `View Key` button. Or you could even just use the `Eye` icon. Clicking on it would display the modal.

Given all that we can simply do the following which makes the table component a lot cleaner.
```
      {
        title: 'Key',
        key: 'key',
        width: '35%',
        render: (entity: ApiKeyModal) => (
        <HiddenAPIKeyModal id={accessKeyId}>View Key</HiddenAPIKeyModal>
        ),
      },
```

2018-11-23 23:21 UTC, chrismccaw commented on src/modules/api-keys/components/table/table.tsx
> +                <CopyKeyButton size="large" type="default" onClick={this.handleCopyKey}>
I think you should use the `primary` type. ` <Button size="large" type="primary" onClick={this.handleCopyKey}>`
That way we are consistent with our buttons throughout the app. Easier the styles later

2018-11-26 15:55 UTC, chrismccaw requested changes
This is looking really good. Just a few things plus some missing tests

2018-11-26 15:55 UTC, chrismccaw commented on src/modules/api-keys/components/modal-hidden-apikey/modal-hidden-apikey.css.tsx
> +export const CopyKeyButton = styled(StyledButton as any)`
Let's just use `StyledButton` at the moment. The designer will take a pass over the dashboard then we will make the changes if needed

2018-11-26 15:55 UTC, chrismccaw commented on src/modules/api-keys/components/table/table.tsx
> +          <HiddenAPIKeyModal id={entity.id}>
This is really cool. Makes table.tsx look a lot cleaner

2018-11-26 15:55 UTC, chrismccaw commented on src/modules/api-keys/components/modal-hidden-apikey/modal-hidden-apikey.tsx
> +    return this.props.apiKeys.filter(item => item.id === this.props.id)[0].key;
Use `find` instead

2018-11-26 15:55 UTC, chrismccaw commented on src/modules/api-keys/components/modal-hidden-apikey/modal-hidden-apikey.tsx
> +              <CopyKeyButton size="large" type="primary" onClick={this.handleCopyKey}>
Use `StyledButton` instead here and remove `CopyKeyButton`

2018-11-26 15:55 UTC, chrismccaw commented on src/modules/api-keys/components/modal-hidden-apikey/modal-hidden-apikey.tsx
> +          <TextArea autosize value={this.getKey()} id="key-textarea" />
Maybe we should put in  this incase the network takes time to return the key

```
<Spin tip="Loading `{API KEY NAME}` Access Key" spinning=(hasApiKey}>
<TextArea autosize value={this.getKey()} id="key-textarea" />
</Spin>
```

2018-11-26 19:59 UTC, chrismccaw requested changes

2018-11-26 19:59 UTC, chrismccaw commented on src/modules/api-keys/components/modal-hidden-apikey/modal-hidden-apikey.tsx
> +    this.props.getKey(this.props.entity.id);
Add `this.props.getKey(this.props.entity.id);` to the `componentDidMount` lifecycle. If you put it here it will be called on every render. This can result in a lot of API calls

2018-11-26 19:59 UTC, chrismccaw commented on src/redux/api-keys/reducer.ts
> +      return { ...state, loading: true, data: updatedData };
Mutating state again - 
All you need it this
`case ApiKeysTypes.REFRESH_KEY_SUCCESS: {
      return { ...state, loading: true, data: state.data.filter(item => item.id === action.payload.id) };
}`

2018-11-26 19:59 UTC, chrismccaw commented on src/redux/api-keys/reducer.ts
> +      state.data.map(obj => {
You are mutating state if you do this. This is bad `obj.key = action.payload.key;`

You should just replace the whole api key object instead of just replacing the `key`

```
const stateWithAccessKey = state.data.map(el => el.id === action.payload.id ? action.payload : el)
return { ...state.data, ...stateWithAccessKey)
```

2018-11-26 20:24 UTC, nscodelover commented on src/modules/api-keys/components/modal-hidden-apikey/modal-hidden-apikey.tsx
> +    this.props.getKey(this.props.entity.id);
yes, I thought so, but there is no way to call `this.props.getKey(...)` when refresh the key if we put it `componentDidMount`.

2018-11-26 20:56 UTC, chrismccaw commented on src/modules/api-keys/components/modal-hidden-apikey/modal-hidden-apikey.tsx
> +    this.props.getKey(this.props.entity.id);
The `componentDidMount` should be called when the modal renders. So after a refresh then clicking on the eye it should call `getKeys` again. We definitely don't want to call any api calls from the render function. API calls should be called from the react lifecycles functions to they are better controlled

2018-11-27 18:45 UTC, chrismccaw requested changes
One minor thing I spotted

2018-11-27 18:45 UTC, chrismccaw commented on src/redux/api-keys/reducer.ts
> +      const stateWithRefreshedKey = state.data.map(
Don't you want to filter out the `payload.id` from state?

2018-11-27 19:17 UTC, chrismccaw approved these changes
👍

2018-11-27 19:21 UTC, merged