Main 179
electricaio/web pull request #27
Opened 2018-11-28 17:48 UTC by renerondon

## [MAIN-179](https://electricaio.atlassian.net/browse/MAIN-179)

## Description

When a user clicks on a connector in the hub it should take them to the connections page.
We should use the breadcrumb component to go back to the connector hub.
We should use react router to navigate between these two screens

2018-11-29 04:42 UTC, chrismccaw requested changes

2018-11-29 04:42 UTC, chrismccaw commented on src/modules/connections/containers/connections.container.tsx
> +    console.log('======', connectors, connector, parseInt(match.params.connectorId, 10));
Remove console log

2018-11-29 04:42 UTC, chrismccaw commented on src/modules/connector-hub/components/card-collection/connector-card.tsx
> +            href={`/#/connector-hub/${connector.id}/connections`}
Use `<Link to` from react router when the button is click

2018-11-29 04:42 UTC, chrismccaw commented on src/routes/dashboard.tsx
> +        <PrivateRoute
Why do we need this route when we have `/connector-hub/:connectorId/connections`?

2018-11-29 04:42 UTC, chrismccaw commented on src/modules/connections/containers/connections.container.tsx
> +    this.props.fetchConnectors();
I wouldn't add this in this PR since we arent using it. In another PR you can add in the communication to the backend

2018-11-29 04:42 UTC, chrismccaw commented on src/modules/connections/containers/connections.container.tsx
> +      [`/connector-hub/${match.params.connectorId}`]: connector && connector.name,
We should only render the breadcrumb and connections component when we actually have a connector. I would wrap this in a spinner and the render the components when we have a connector

2018-11-29 11:31 UTC, renerondon commented on src/modules/connections/containers/connections.container.tsx
> +      [`/connector-hub/${match.params.connectorId}`]: connector && connector.name,
My changes block the error from getting property from undefined object.

2018-11-30 20:06 UTC, chrismccaw approved these changes

2018-11-30 20:06 UTC, merged