Fature/main 78 typescript
electricaio/web pull request #3
Opened 2018-10-12 17:25 UTC by paschenkov-electrica

## [MAIN-78]https://electricaio.atlassian.net/browse/MAIN-78

Add TS, rewrite all components to TS, reconfigure a project

2018-10-12 17:36 UTC, inder-zz commented
no coveralls?

2018-10-13 02:02 UTC, chrismccaw requested changes
I think this is pretty good. Just some things around structure and linting. There are some stuff in there that linting should have caught. For example We are mixing single and double quotes when importing and no new lines at end of the file. 

I tried to run the app but got this error

```
Error: Cannot find module 'uri-js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/cmccaw/Projects/electrica/web/node_modules/eslint/node_modules/ajv/lib/compile/resolve.js:3:11)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
error Command failed with exit code 1.
```

2018-10-13 02:02 UTC, chrismccaw commented on .prettierrc
> +{
The prettier config is already defined in `.eslintrc.js` I had some weird problems having it in this rc and was causing the `npm run format` to do the wrong formatting

2018-10-13 02:02 UTC, chrismccaw commented on src/models/ApiKeyTableEntity.ts
> +};
No Newline at end of this file should have been caught by the linter

2018-10-13 02:02 UTC, chrismccaw commented on src/modules/shared-components/layout/electrica-layout.tsx
> +export class ElectricaLayout extends Component<TElectriceLayoutProps> {
I wouldn't call this electrica layout. I think this is more the `main-layout` after we are logged in. The layouts should belong in the `pages` directory. Then use the stuff `modules` to bring the behavior. That way we can keep the initial page structure separate from the content

2018-10-13 02:02 UTC, chrismccaw commented on src/modules/shared-components/layout/electrica-layout.tsx
> +export function headerNavigationItems() {
We should probably pull this out to a component but that can be in another PR

2018-10-13 02:02 UTC, chrismccaw commented on src/redux/reducers/api-keys.ts
> +  switch (action.type) {
Ah I wish we could use `redux-actions` to avoid this ugly switch

2018-10-13 02:02 UTC, chrismccaw commented on src/redux/reducers/api-keys.ts
> +      return true;
Why do we need this reducer?

2018-10-13 02:02 UTC, chrismccaw commented on src/redux/reducers/index.ts
> +  data: keyReducer,
we should have `apiKeys: keysReducer `. `data` is too general and will cause confusion when we add more reducers

2018-10-13 02:02 UTC, chrismccaw commented on src/redux/store.ts
> +  return createStore<TAppState, TAction, {}, {}>(rootReducer, initialState);
yeh promise middleware is a must

2018-10-13 02:02 UTC, chrismccaw commented on src/storybook/api-keys.story.tsx
> +storiesOf('Button', module)
Kind of unnecessary for this PR. I don't think we need this yet

2018-10-13 02:02 UTC, chrismccaw commented on .travis.yml
> +before_script: npm run tslint
We want to ensure eslint and tslint run, not just typescript. I would keep `npm run lint` but maybe use `concurrently` to run both eslint and tslint together

2018-10-13 02:02 UTC, chrismccaw commented on tslint.json
> +        "tslint-config-airbnb"
We should also extend `tslint-react` and/or `tslint-microsoft-contrib`. Or does the airbnb cover those?

2018-10-14 19:25 UTC, paschenkov-electrica commented on src/modules/shared-components/layout/electrica-layout.tsx
> +export class ElectricaLayout extends Component<TElectriceLayoutProps> {
1) **I think this is more the main-layout**
Looks like we don't need any other layout, but if/when we will need it, we can rename current layout (if it will be needed, but I think it will not).
_Anyway, it's just a name, so I can call it as you ask_

2) **The layouts should belong in the pages directory** 
If we have something which doesn't fit in `ui-kit components` but still should be shared (like Layout and Navigation), It's a good practice to place such components in `shared module` or just create it as a separate module. 

It's really cool to keep the initial page structure separate from the content, moreover, I want the same! 
But as I know `modules` provides all components stuff. Even `ui-kit` should be placed in `modules`, or moving to a separate package (using monorepo & lerna for example)

**P.s.** I'm not trying to push any of my ideas, it's just a proposal for discussion

2018-10-14 19:26 UTC, paschenkov-electrica commented on src/redux/reducers/api-keys.ts
> +  switch (action.type) {
me too, me too... but unfortunately we should provide many types in redux...

2018-10-14 19:28 UTC, paschenkov-electrica commented on src/storybook/api-keys.story.tsx
> +storiesOf('Button', module)
right, forgot to remove, ty

2018-10-14 19:38 UTC, paschenkov-electrica commented on .prettierrc
> +{
We have `ESLint`, `TSLint` and `Prettier` and this is different tools, so I think it will be better to store config separately. 

Btw, if we have a separate config for each tool, IDE / Code editors extensions should work well. At least I have had problems with prettier in WebStorm - extension used wrong rules.

**P.s.**
Think I should clean up in `.eslintrc`, what do you think?

2018-10-14 19:39 UTC, paschenkov-electrica commented on src/models/ApiKeyTableEntity.ts
> +};
yeah, my bad, i'll fix it, ty

2018-10-14 19:41 UTC, paschenkov-electrica commented on src/modules/shared-components/layout/electrica-layout.tsx
> +export function headerNavigationItems() {
but this is just a helper function - to pull this out we need to refactor `Navigation` component...

2018-10-14 19:42 UTC, paschenkov-electrica commented on src/redux/reducers/index.ts
> +  data: keyReducer,
👍

2018-10-14 19:59 UTC, chrismccaw commented on .prettierrc
> +{
Yeh it is more of a cleanup. I see eslint.js has prettier config but we also have a .prettierrc

2018-10-14 20:00 UTC, chrismccaw commented on src/modules/shared-components/layout/electrica-layout.tsx
> +export function headerNavigationItems() {
Yeh we don't need to do this now.

2018-10-14 20:00 UTC, chrismccaw commented on src/storybook/api-keys.story.tsx
> +storiesOf('Button', module)
We can create a separate story for `storybook`

2018-10-14 20:04 UTC, chrismccaw commented on src/modules/shared-components/layout/electrica-layout.tsx
> +export class ElectricaLayout extends Component<TElectriceLayoutProps> {
We will have a few layouts. I'm actually working with another layout for signup/login because it doesn't require the nav bar. I think we might have a mix of layouts. For example layouts with a sidebar, without a sidebar. Also a layout with a nav bar.

I like the idea of layouts being close to where the pages are defined. So we create the `page` with the layout structure and then fill the page with components from `modules`. I think that would be a good pattern to use

2018-10-14 20:16 UTC, paschenkov-electrica commented on .travis.yml
> +before_script: npm run tslint
sounds good, I'll add it. 
But without concurrently - anyway, we need `build scripts` optimization, so I think we can improve this in a separate task.

2018-10-14 20:36 UTC, paschenkov-electrica commented on tslint.json
> +        "tslint-config-airbnb"
Too restricted rules sets...

Maybe it's better to add a few rules manually if you need these?
Or we can discuss each of them in a slack, for example

2018-10-14 20:57 UTC, chrismccaw commented on tslint.json
> +        "tslint-config-airbnb"
I think we can add a few rules manually. For example we should be failing on no new line and mixing import quotes . We can discuss on slack tho

2018-10-15 01:50 UTC, paschenkov-electrica commented on src/storybook/api-keys.story.tsx
> +storiesOf('Button', module)
Yeah, I'll do it

2018-10-15 02:41 UTC, paschenkov-electrica commented on tslint.json
> +        "tslint-config-airbnb"
we already should fail in such cases - I've fixed scripts, now it works well

2018-10-15 04:37 UTC, paschenkov-electrica commented on src/redux/store.ts
> +  return createStore<TAppState, TAction, {}, {}>(rootReducer, initialState);
👍

2018-10-15 04:40 UTC, paschenkov-electrica commented on src/redux/reducers/api-keys.ts
> +      return true;
right, removed

2018-10-15 20:17 UTC, chrismccaw approved these changes
Nice work. Looks good

2018-10-15 20:17 UTC, merged